fragment GlobalParts on Global {
  __typename
  nav {
    __typename
    links {
      __typename
      label
      href
      isCta
    }
  }
  footer {
    __typename
    tags
    copyright
  }
}

fragment HomeParts on Home {
  __typename
  hero {
    __typename
    badge
    line1
    line2Prefix
    cyclingWords
    sub
    primaryCtaLabel
    primaryCtaHref
    ghostCtaLabel
    ghostCtaHref
  }
  problem {
    __typename
    heading
    headingMuted
    body
  }
  services {
    __typename
    sectionLabel
    heading
    ctaLabel
    ctaHref
    cards {
      __typename
      number
      title
      description
      featured
      bullets
    }
  }
  process {
    __typename
    title
    steps {
      __typename
      title
      body
    }
  }
  authority {
    __typename
    sectionLabel
    heading
    body
  }
  contact {
    __typename
    heading
    intro
    serviceOptions
    submitLabel
  }
}

fragment FounderParts on Founder {
  __typename
  eyebrow
  heroTitle
  heroTitleMuted
  heroSub
  primaryCtaLabel
  primaryCtaHref
  ghostCtaLabel
  ghostCtaHref
  founderName
  founderTitle
  founderPhoto
  sidebarLabel
  sidebarTags
  content {
    __typename
    ... on FounderContentParagraph {
      text
    }
    ... on FounderContentPullQuote {
      text
    }
  }
  cta {
    __typename
    label
    heading
    headingGradient
    sub
    primaryCtaLabel
    primaryCtaHref
    ghostCtaLabel
    ghostCtaHref
  }
}

fragment WorkParts on Work {
  __typename
  title
  titleMuted
  lead
  metaPills {
    __typename
    label
    highlight
  }
  overview {
    __typename
    label
    value
  }
  sections {
    __typename
    sectionLabel
    navLabel
    heading
    paragraphs
    callout {
      __typename
      type
      label
      body
    }
    beforeItems
    afterItems
    deliverables
    pullQuote {
      __typename
      text
      attribution
    }
  }
  cta {
    __typename
    sectionLabel
    heading
    headingGradient
    sub
  }
}
