//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  global: Global;
  globalConnection: GlobalConnection;
  home: Home;
  homeConnection: HomeConnection;
  founder: Founder;
  founderConnection: FounderConnection;
  work: Work;
  workConnection: WorkConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGlobalArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGlobalConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GlobalFilter>;
};


export type QueryHomeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
};


export type QueryFounderArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFounderConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FounderFilter>;
};


export type QueryWorkArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryWorkConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<WorkFilter>;
};

export type DocumentFilter = {
  global?: InputMaybe<GlobalFilter>;
  home?: InputMaybe<HomeFilter>;
  founder?: InputMaybe<FounderFilter>;
  work?: InputMaybe<WorkFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Global | Home | Founder | Work | Folder;

export type GlobalNavLinks = {
  __typename?: 'GlobalNavLinks';
  label?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
  isCta?: Maybe<Scalars['Boolean']['output']>;
};

export type GlobalNav = {
  __typename?: 'GlobalNav';
  links?: Maybe<Array<Maybe<GlobalNavLinks>>>;
};

export type GlobalFooter = {
  __typename?: 'GlobalFooter';
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  copyright?: Maybe<Scalars['String']['output']>;
};

export type Global = Node & Document & {
  __typename?: 'Global';
  nav?: Maybe<GlobalNav>;
  footer?: Maybe<GlobalFooter>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type GlobalNavLinksFilter = {
  label?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
  isCta?: InputMaybe<BooleanFilter>;
};

export type GlobalNavFilter = {
  links?: InputMaybe<GlobalNavLinksFilter>;
};

export type GlobalFooterFilter = {
  tags?: InputMaybe<StringFilter>;
  copyright?: InputMaybe<StringFilter>;
};

export type GlobalFilter = {
  nav?: InputMaybe<GlobalNavFilter>;
  footer?: InputMaybe<GlobalFooterFilter>;
};

export type GlobalConnectionEdges = {
  __typename?: 'GlobalConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Global>;
};

export type GlobalConnection = Connection & {
  __typename?: 'GlobalConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<GlobalConnectionEdges>>>;
};

export type HomeHero = {
  __typename?: 'HomeHero';
  badge?: Maybe<Scalars['String']['output']>;
  line1?: Maybe<Scalars['String']['output']>;
  line2Prefix?: Maybe<Scalars['String']['output']>;
  cyclingWords?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  sub?: Maybe<Scalars['String']['output']>;
  primaryCtaLabel?: Maybe<Scalars['String']['output']>;
  primaryCtaHref?: Maybe<Scalars['String']['output']>;
  ghostCtaLabel?: Maybe<Scalars['String']['output']>;
  ghostCtaHref?: Maybe<Scalars['String']['output']>;
};

export type HomeProblem = {
  __typename?: 'HomeProblem';
  heading?: Maybe<Scalars['String']['output']>;
  headingMuted?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
};

export type HomeServicesCards = {
  __typename?: 'HomeServicesCards';
  number?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  featured?: Maybe<Scalars['Boolean']['output']>;
  bullets?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type HomeServices = {
  __typename?: 'HomeServices';
  sectionLabel?: Maybe<Scalars['String']['output']>;
  heading?: Maybe<Scalars['String']['output']>;
  ctaLabel?: Maybe<Scalars['String']['output']>;
  ctaHref?: Maybe<Scalars['String']['output']>;
  cards?: Maybe<Array<Maybe<HomeServicesCards>>>;
};

export type HomeProcessSteps = {
  __typename?: 'HomeProcessSteps';
  title?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
};

export type HomeProcess = {
  __typename?: 'HomeProcess';
  title?: Maybe<Scalars['String']['output']>;
  steps?: Maybe<Array<Maybe<HomeProcessSteps>>>;
};

export type HomeAuthority = {
  __typename?: 'HomeAuthority';
  sectionLabel?: Maybe<Scalars['String']['output']>;
  heading?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
};

export type HomeContact = {
  __typename?: 'HomeContact';
  heading?: Maybe<Scalars['String']['output']>;
  intro?: Maybe<Scalars['String']['output']>;
  serviceOptions?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  submitLabel?: Maybe<Scalars['String']['output']>;
};

export type Home = Node & Document & {
  __typename?: 'Home';
  hero?: Maybe<HomeHero>;
  problem?: Maybe<HomeProblem>;
  services?: Maybe<HomeServices>;
  process?: Maybe<HomeProcess>;
  authority?: Maybe<HomeAuthority>;
  contact?: Maybe<HomeContact>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type HomeHeroFilter = {
  badge?: InputMaybe<StringFilter>;
  line1?: InputMaybe<StringFilter>;
  line2Prefix?: InputMaybe<StringFilter>;
  cyclingWords?: InputMaybe<StringFilter>;
  sub?: InputMaybe<StringFilter>;
  primaryCtaLabel?: InputMaybe<StringFilter>;
  primaryCtaHref?: InputMaybe<StringFilter>;
  ghostCtaLabel?: InputMaybe<StringFilter>;
  ghostCtaHref?: InputMaybe<StringFilter>;
};

export type HomeProblemFilter = {
  heading?: InputMaybe<StringFilter>;
  headingMuted?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
};

export type HomeServicesCardsFilter = {
  number?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  featured?: InputMaybe<BooleanFilter>;
  bullets?: InputMaybe<StringFilter>;
};

export type HomeServicesFilter = {
  sectionLabel?: InputMaybe<StringFilter>;
  heading?: InputMaybe<StringFilter>;
  ctaLabel?: InputMaybe<StringFilter>;
  ctaHref?: InputMaybe<StringFilter>;
  cards?: InputMaybe<HomeServicesCardsFilter>;
};

export type HomeProcessStepsFilter = {
  title?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
};

export type HomeProcessFilter = {
  title?: InputMaybe<StringFilter>;
  steps?: InputMaybe<HomeProcessStepsFilter>;
};

export type HomeAuthorityFilter = {
  sectionLabel?: InputMaybe<StringFilter>;
  heading?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
};

export type HomeContactFilter = {
  heading?: InputMaybe<StringFilter>;
  intro?: InputMaybe<StringFilter>;
  serviceOptions?: InputMaybe<StringFilter>;
  submitLabel?: InputMaybe<StringFilter>;
};

export type HomeFilter = {
  hero?: InputMaybe<HomeHeroFilter>;
  problem?: InputMaybe<HomeProblemFilter>;
  services?: InputMaybe<HomeServicesFilter>;
  process?: InputMaybe<HomeProcessFilter>;
  authority?: InputMaybe<HomeAuthorityFilter>;
  contact?: InputMaybe<HomeContactFilter>;
};

export type HomeConnectionEdges = {
  __typename?: 'HomeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Home>;
};

export type HomeConnection = Connection & {
  __typename?: 'HomeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomeConnectionEdges>>>;
};

export type FounderContentParagraph = {
  __typename?: 'FounderContentParagraph';
  text?: Maybe<Scalars['String']['output']>;
};

export type FounderContentPullQuote = {
  __typename?: 'FounderContentPullQuote';
  text?: Maybe<Scalars['String']['output']>;
};

export type FounderContent = FounderContentParagraph | FounderContentPullQuote;

export type FounderCta = {
  __typename?: 'FounderCta';
  label?: Maybe<Scalars['String']['output']>;
  heading?: Maybe<Scalars['String']['output']>;
  headingGradient?: Maybe<Scalars['String']['output']>;
  sub?: Maybe<Scalars['String']['output']>;
  primaryCtaLabel?: Maybe<Scalars['String']['output']>;
  primaryCtaHref?: Maybe<Scalars['String']['output']>;
  ghostCtaLabel?: Maybe<Scalars['String']['output']>;
  ghostCtaHref?: Maybe<Scalars['String']['output']>;
};

export type Founder = Node & Document & {
  __typename?: 'Founder';
  eyebrow?: Maybe<Scalars['String']['output']>;
  heroTitle?: Maybe<Scalars['String']['output']>;
  heroTitleMuted?: Maybe<Scalars['String']['output']>;
  heroSub?: Maybe<Scalars['String']['output']>;
  primaryCtaLabel?: Maybe<Scalars['String']['output']>;
  primaryCtaHref?: Maybe<Scalars['String']['output']>;
  ghostCtaLabel?: Maybe<Scalars['String']['output']>;
  ghostCtaHref?: Maybe<Scalars['String']['output']>;
  founderName?: Maybe<Scalars['String']['output']>;
  founderTitle?: Maybe<Scalars['String']['output']>;
  founderPhoto?: Maybe<Scalars['String']['output']>;
  sidebarLabel?: Maybe<Scalars['String']['output']>;
  sidebarTags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  content?: Maybe<Array<Maybe<FounderContent>>>;
  cta?: Maybe<FounderCta>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type FounderContentParagraphFilter = {
  text?: InputMaybe<StringFilter>;
};

export type FounderContentPullQuoteFilter = {
  text?: InputMaybe<StringFilter>;
};

export type FounderContentFilter = {
  paragraph?: InputMaybe<FounderContentParagraphFilter>;
  pullQuote?: InputMaybe<FounderContentPullQuoteFilter>;
};

export type FounderCtaFilter = {
  label?: InputMaybe<StringFilter>;
  heading?: InputMaybe<StringFilter>;
  headingGradient?: InputMaybe<StringFilter>;
  sub?: InputMaybe<StringFilter>;
  primaryCtaLabel?: InputMaybe<StringFilter>;
  primaryCtaHref?: InputMaybe<StringFilter>;
  ghostCtaLabel?: InputMaybe<StringFilter>;
  ghostCtaHref?: InputMaybe<StringFilter>;
};

export type FounderFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  heroTitle?: InputMaybe<StringFilter>;
  heroTitleMuted?: InputMaybe<StringFilter>;
  heroSub?: InputMaybe<StringFilter>;
  primaryCtaLabel?: InputMaybe<StringFilter>;
  primaryCtaHref?: InputMaybe<StringFilter>;
  ghostCtaLabel?: InputMaybe<StringFilter>;
  ghostCtaHref?: InputMaybe<StringFilter>;
  founderName?: InputMaybe<StringFilter>;
  founderTitle?: InputMaybe<StringFilter>;
  founderPhoto?: InputMaybe<ImageFilter>;
  sidebarLabel?: InputMaybe<StringFilter>;
  sidebarTags?: InputMaybe<StringFilter>;
  content?: InputMaybe<FounderContentFilter>;
  cta?: InputMaybe<FounderCtaFilter>;
};

export type FounderConnectionEdges = {
  __typename?: 'FounderConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Founder>;
};

export type FounderConnection = Connection & {
  __typename?: 'FounderConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<FounderConnectionEdges>>>;
};

export type WorkMetaPills = {
  __typename?: 'WorkMetaPills';
  label?: Maybe<Scalars['String']['output']>;
  highlight?: Maybe<Scalars['Boolean']['output']>;
};

export type WorkOverview = {
  __typename?: 'WorkOverview';
  label?: Maybe<Scalars['String']['output']>;
  value?: Maybe<Scalars['String']['output']>;
};

export type WorkSectionsCallout = {
  __typename?: 'WorkSectionsCallout';
  type?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
};

export type WorkSectionsPullQuote = {
  __typename?: 'WorkSectionsPullQuote';
  text?: Maybe<Scalars['String']['output']>;
  attribution?: Maybe<Scalars['String']['output']>;
};

export type WorkSections = {
  __typename?: 'WorkSections';
  sectionLabel?: Maybe<Scalars['String']['output']>;
  navLabel?: Maybe<Scalars['String']['output']>;
  heading?: Maybe<Scalars['String']['output']>;
  paragraphs?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  callout?: Maybe<WorkSectionsCallout>;
  beforeItems?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  afterItems?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  deliverables?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  pullQuote?: Maybe<WorkSectionsPullQuote>;
};

export type WorkCta = {
  __typename?: 'WorkCta';
  sectionLabel?: Maybe<Scalars['String']['output']>;
  heading?: Maybe<Scalars['String']['output']>;
  headingGradient?: Maybe<Scalars['String']['output']>;
  sub?: Maybe<Scalars['String']['output']>;
};

export type Work = Node & Document & {
  __typename?: 'Work';
  title?: Maybe<Scalars['String']['output']>;
  titleMuted?: Maybe<Scalars['String']['output']>;
  lead?: Maybe<Scalars['String']['output']>;
  metaPills?: Maybe<Array<Maybe<WorkMetaPills>>>;
  overview?: Maybe<Array<Maybe<WorkOverview>>>;
  sections?: Maybe<Array<Maybe<WorkSections>>>;
  cta?: Maybe<WorkCta>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type WorkMetaPillsFilter = {
  label?: InputMaybe<StringFilter>;
  highlight?: InputMaybe<BooleanFilter>;
};

export type WorkOverviewFilter = {
  label?: InputMaybe<StringFilter>;
  value?: InputMaybe<StringFilter>;
};

export type WorkSectionsCalloutFilter = {
  type?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
};

export type WorkSectionsPullQuoteFilter = {
  text?: InputMaybe<StringFilter>;
  attribution?: InputMaybe<StringFilter>;
};

export type WorkSectionsFilter = {
  sectionLabel?: InputMaybe<StringFilter>;
  navLabel?: InputMaybe<StringFilter>;
  heading?: InputMaybe<StringFilter>;
  paragraphs?: InputMaybe<StringFilter>;
  callout?: InputMaybe<WorkSectionsCalloutFilter>;
  beforeItems?: InputMaybe<StringFilter>;
  afterItems?: InputMaybe<StringFilter>;
  deliverables?: InputMaybe<StringFilter>;
  pullQuote?: InputMaybe<WorkSectionsPullQuoteFilter>;
};

export type WorkCtaFilter = {
  sectionLabel?: InputMaybe<StringFilter>;
  heading?: InputMaybe<StringFilter>;
  headingGradient?: InputMaybe<StringFilter>;
  sub?: InputMaybe<StringFilter>;
};

export type WorkFilter = {
  title?: InputMaybe<StringFilter>;
  titleMuted?: InputMaybe<StringFilter>;
  lead?: InputMaybe<StringFilter>;
  metaPills?: InputMaybe<WorkMetaPillsFilter>;
  overview?: InputMaybe<WorkOverviewFilter>;
  sections?: InputMaybe<WorkSectionsFilter>;
  cta?: InputMaybe<WorkCtaFilter>;
};

export type WorkConnectionEdges = {
  __typename?: 'WorkConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Work>;
};

export type WorkConnection = Connection & {
  __typename?: 'WorkConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<WorkConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateGlobal: Global;
  createGlobal: Global;
  updateHome: Home;
  createHome: Home;
  updateFounder: Founder;
  createFounder: Founder;
  updateWork: Work;
  createWork: Work;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateGlobalArgs = {
  relativePath: Scalars['String']['input'];
  params: GlobalMutation;
};


export type MutationCreateGlobalArgs = {
  relativePath: Scalars['String']['input'];
  params: GlobalMutation;
};


export type MutationUpdateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationCreateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationUpdateFounderArgs = {
  relativePath: Scalars['String']['input'];
  params: FounderMutation;
};


export type MutationCreateFounderArgs = {
  relativePath: Scalars['String']['input'];
  params: FounderMutation;
};


export type MutationUpdateWorkArgs = {
  relativePath: Scalars['String']['input'];
  params: WorkMutation;
};


export type MutationCreateWorkArgs = {
  relativePath: Scalars['String']['input'];
  params: WorkMutation;
};

export type DocumentUpdateMutation = {
  global?: InputMaybe<GlobalMutation>;
  home?: InputMaybe<HomeMutation>;
  founder?: InputMaybe<FounderMutation>;
  work?: InputMaybe<WorkMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  global?: InputMaybe<GlobalMutation>;
  home?: InputMaybe<HomeMutation>;
  founder?: InputMaybe<FounderMutation>;
  work?: InputMaybe<WorkMutation>;
};

export type GlobalNavLinksMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
  isCta?: InputMaybe<Scalars['Boolean']['input']>;
};

export type GlobalNavMutation = {
  links?: InputMaybe<Array<InputMaybe<GlobalNavLinksMutation>>>;
};

export type GlobalFooterMutation = {
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  copyright?: InputMaybe<Scalars['String']['input']>;
};

export type GlobalMutation = {
  nav?: InputMaybe<GlobalNavMutation>;
  footer?: InputMaybe<GlobalFooterMutation>;
};

export type HomeHeroMutation = {
  badge?: InputMaybe<Scalars['String']['input']>;
  line1?: InputMaybe<Scalars['String']['input']>;
  line2Prefix?: InputMaybe<Scalars['String']['input']>;
  cyclingWords?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  sub?: InputMaybe<Scalars['String']['input']>;
  primaryCtaLabel?: InputMaybe<Scalars['String']['input']>;
  primaryCtaHref?: InputMaybe<Scalars['String']['input']>;
  ghostCtaLabel?: InputMaybe<Scalars['String']['input']>;
  ghostCtaHref?: InputMaybe<Scalars['String']['input']>;
};

export type HomeProblemMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  headingMuted?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
};

export type HomeServicesCardsMutation = {
  number?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
  bullets?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomeServicesMutation = {
  sectionLabel?: InputMaybe<Scalars['String']['input']>;
  heading?: InputMaybe<Scalars['String']['input']>;
  ctaLabel?: InputMaybe<Scalars['String']['input']>;
  ctaHref?: InputMaybe<Scalars['String']['input']>;
  cards?: InputMaybe<Array<InputMaybe<HomeServicesCardsMutation>>>;
};

export type HomeProcessStepsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
};

export type HomeProcessMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  steps?: InputMaybe<Array<InputMaybe<HomeProcessStepsMutation>>>;
};

export type HomeAuthorityMutation = {
  sectionLabel?: InputMaybe<Scalars['String']['input']>;
  heading?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
};

export type HomeContactMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  intro?: InputMaybe<Scalars['String']['input']>;
  serviceOptions?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  submitLabel?: InputMaybe<Scalars['String']['input']>;
};

export type HomeMutation = {
  hero?: InputMaybe<HomeHeroMutation>;
  problem?: InputMaybe<HomeProblemMutation>;
  services?: InputMaybe<HomeServicesMutation>;
  process?: InputMaybe<HomeProcessMutation>;
  authority?: InputMaybe<HomeAuthorityMutation>;
  contact?: InputMaybe<HomeContactMutation>;
};

export type FounderContentParagraphMutation = {
  text?: InputMaybe<Scalars['String']['input']>;
};

export type FounderContentPullQuoteMutation = {
  text?: InputMaybe<Scalars['String']['input']>;
};

export type FounderContentMutation = {
  paragraph?: InputMaybe<FounderContentParagraphMutation>;
  pullQuote?: InputMaybe<FounderContentPullQuoteMutation>;
};

export type FounderCtaMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  heading?: InputMaybe<Scalars['String']['input']>;
  headingGradient?: InputMaybe<Scalars['String']['input']>;
  sub?: InputMaybe<Scalars['String']['input']>;
  primaryCtaLabel?: InputMaybe<Scalars['String']['input']>;
  primaryCtaHref?: InputMaybe<Scalars['String']['input']>;
  ghostCtaLabel?: InputMaybe<Scalars['String']['input']>;
  ghostCtaHref?: InputMaybe<Scalars['String']['input']>;
};

export type FounderMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  heroTitle?: InputMaybe<Scalars['String']['input']>;
  heroTitleMuted?: InputMaybe<Scalars['String']['input']>;
  heroSub?: InputMaybe<Scalars['String']['input']>;
  primaryCtaLabel?: InputMaybe<Scalars['String']['input']>;
  primaryCtaHref?: InputMaybe<Scalars['String']['input']>;
  ghostCtaLabel?: InputMaybe<Scalars['String']['input']>;
  ghostCtaHref?: InputMaybe<Scalars['String']['input']>;
  founderName?: InputMaybe<Scalars['String']['input']>;
  founderTitle?: InputMaybe<Scalars['String']['input']>;
  founderPhoto?: InputMaybe<Scalars['String']['input']>;
  sidebarLabel?: InputMaybe<Scalars['String']['input']>;
  sidebarTags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  content?: InputMaybe<Array<InputMaybe<FounderContentMutation>>>;
  cta?: InputMaybe<FounderCtaMutation>;
};

export type WorkMetaPillsMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  highlight?: InputMaybe<Scalars['Boolean']['input']>;
};

export type WorkOverviewMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  value?: InputMaybe<Scalars['String']['input']>;
};

export type WorkSectionsCalloutMutation = {
  type?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
};

export type WorkSectionsPullQuoteMutation = {
  text?: InputMaybe<Scalars['String']['input']>;
  attribution?: InputMaybe<Scalars['String']['input']>;
};

export type WorkSectionsMutation = {
  sectionLabel?: InputMaybe<Scalars['String']['input']>;
  navLabel?: InputMaybe<Scalars['String']['input']>;
  heading?: InputMaybe<Scalars['String']['input']>;
  paragraphs?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  callout?: InputMaybe<WorkSectionsCalloutMutation>;
  beforeItems?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  afterItems?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  deliverables?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  pullQuote?: InputMaybe<WorkSectionsPullQuoteMutation>;
};

export type WorkCtaMutation = {
  sectionLabel?: InputMaybe<Scalars['String']['input']>;
  heading?: InputMaybe<Scalars['String']['input']>;
  headingGradient?: InputMaybe<Scalars['String']['input']>;
  sub?: InputMaybe<Scalars['String']['input']>;
};

export type WorkMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  titleMuted?: InputMaybe<Scalars['String']['input']>;
  lead?: InputMaybe<Scalars['String']['input']>;
  metaPills?: InputMaybe<Array<InputMaybe<WorkMetaPillsMutation>>>;
  overview?: InputMaybe<Array<InputMaybe<WorkOverviewMutation>>>;
  sections?: InputMaybe<Array<InputMaybe<WorkSectionsMutation>>>;
  cta?: InputMaybe<WorkCtaMutation>;
};

export type GlobalPartsFragment = { __typename: 'Global', nav?: { __typename: 'GlobalNav', links?: Array<{ __typename: 'GlobalNavLinks', label?: string | null, href?: string | null, isCta?: boolean | null } | null> | null } | null, footer?: { __typename: 'GlobalFooter', tags?: Array<string | null> | null, copyright?: string | null } | null };

export type HomePartsFragment = { __typename: 'Home', hero?: { __typename: 'HomeHero', badge?: string | null, line1?: string | null, line2Prefix?: string | null, cyclingWords?: Array<string | null> | null, sub?: string | null, primaryCtaLabel?: string | null, primaryCtaHref?: string | null, ghostCtaLabel?: string | null, ghostCtaHref?: string | null } | null, problem?: { __typename: 'HomeProblem', heading?: string | null, headingMuted?: string | null, body?: string | null } | null, services?: { __typename: 'HomeServices', sectionLabel?: string | null, heading?: string | null, ctaLabel?: string | null, ctaHref?: string | null, cards?: Array<{ __typename: 'HomeServicesCards', number?: string | null, title?: string | null, description?: string | null, featured?: boolean | null, bullets?: Array<string | null> | null } | null> | null } | null, process?: { __typename: 'HomeProcess', title?: string | null, steps?: Array<{ __typename: 'HomeProcessSteps', title?: string | null, body?: string | null } | null> | null } | null, authority?: { __typename: 'HomeAuthority', sectionLabel?: string | null, heading?: string | null, body?: string | null } | null, contact?: { __typename: 'HomeContact', heading?: string | null, intro?: string | null, serviceOptions?: Array<string | null> | null, submitLabel?: string | null } | null };

export type FounderPartsFragment = { __typename: 'Founder', eyebrow?: string | null, heroTitle?: string | null, heroTitleMuted?: string | null, heroSub?: string | null, primaryCtaLabel?: string | null, primaryCtaHref?: string | null, ghostCtaLabel?: string | null, ghostCtaHref?: string | null, founderName?: string | null, founderTitle?: string | null, founderPhoto?: string | null, sidebarLabel?: string | null, sidebarTags?: Array<string | null> | null, content?: Array<{ __typename: 'FounderContentParagraph', text?: string | null } | { __typename: 'FounderContentPullQuote', text?: string | null } | null> | null, cta?: { __typename: 'FounderCta', label?: string | null, heading?: string | null, headingGradient?: string | null, sub?: string | null, primaryCtaLabel?: string | null, primaryCtaHref?: string | null, ghostCtaLabel?: string | null, ghostCtaHref?: string | null } | null };

export type WorkPartsFragment = { __typename: 'Work', title?: string | null, titleMuted?: string | null, lead?: string | null, metaPills?: Array<{ __typename: 'WorkMetaPills', label?: string | null, highlight?: boolean | null } | null> | null, overview?: Array<{ __typename: 'WorkOverview', label?: string | null, value?: string | null } | null> | null, sections?: Array<{ __typename: 'WorkSections', sectionLabel?: string | null, navLabel?: string | null, heading?: string | null, paragraphs?: Array<string | null> | null, beforeItems?: Array<string | null> | null, afterItems?: Array<string | null> | null, deliverables?: Array<string | null> | null, callout?: { __typename: 'WorkSectionsCallout', type?: string | null, label?: string | null, body?: string | null } | null, pullQuote?: { __typename: 'WorkSectionsPullQuote', text?: string | null, attribution?: string | null } | null } | null> | null, cta?: { __typename: 'WorkCta', sectionLabel?: string | null, heading?: string | null, headingGradient?: string | null, sub?: string | null } | null };

export type GlobalQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type GlobalQuery = { __typename?: 'Query', global: { __typename: 'Global', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, nav?: { __typename: 'GlobalNav', links?: Array<{ __typename: 'GlobalNavLinks', label?: string | null, href?: string | null, isCta?: boolean | null } | null> | null } | null, footer?: { __typename: 'GlobalFooter', tags?: Array<string | null> | null, copyright?: string | null } | null } };

export type GlobalConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GlobalFilter>;
}>;


export type GlobalConnectionQuery = { __typename?: 'Query', globalConnection: { __typename?: 'GlobalConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'GlobalConnectionEdges', cursor: string, node?: { __typename: 'Global', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, nav?: { __typename: 'GlobalNav', links?: Array<{ __typename: 'GlobalNavLinks', label?: string | null, href?: string | null, isCta?: boolean | null } | null> | null } | null, footer?: { __typename: 'GlobalFooter', tags?: Array<string | null> | null, copyright?: string | null } | null } | null } | null> | null } };

export type HomeQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomeQuery = { __typename?: 'Query', home: { __typename: 'Home', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'HomeHero', badge?: string | null, line1?: string | null, line2Prefix?: string | null, cyclingWords?: Array<string | null> | null, sub?: string | null, primaryCtaLabel?: string | null, primaryCtaHref?: string | null, ghostCtaLabel?: string | null, ghostCtaHref?: string | null } | null, problem?: { __typename: 'HomeProblem', heading?: string | null, headingMuted?: string | null, body?: string | null } | null, services?: { __typename: 'HomeServices', sectionLabel?: string | null, heading?: string | null, ctaLabel?: string | null, ctaHref?: string | null, cards?: Array<{ __typename: 'HomeServicesCards', number?: string | null, title?: string | null, description?: string | null, featured?: boolean | null, bullets?: Array<string | null> | null } | null> | null } | null, process?: { __typename: 'HomeProcess', title?: string | null, steps?: Array<{ __typename: 'HomeProcessSteps', title?: string | null, body?: string | null } | null> | null } | null, authority?: { __typename: 'HomeAuthority', sectionLabel?: string | null, heading?: string | null, body?: string | null } | null, contact?: { __typename: 'HomeContact', heading?: string | null, intro?: string | null, serviceOptions?: Array<string | null> | null, submitLabel?: string | null } | null } };

export type HomeConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
}>;


export type HomeConnectionQuery = { __typename?: 'Query', homeConnection: { __typename?: 'HomeConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomeConnectionEdges', cursor: string, node?: { __typename: 'Home', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'HomeHero', badge?: string | null, line1?: string | null, line2Prefix?: string | null, cyclingWords?: Array<string | null> | null, sub?: string | null, primaryCtaLabel?: string | null, primaryCtaHref?: string | null, ghostCtaLabel?: string | null, ghostCtaHref?: string | null } | null, problem?: { __typename: 'HomeProblem', heading?: string | null, headingMuted?: string | null, body?: string | null } | null, services?: { __typename: 'HomeServices', sectionLabel?: string | null, heading?: string | null, ctaLabel?: string | null, ctaHref?: string | null, cards?: Array<{ __typename: 'HomeServicesCards', number?: string | null, title?: string | null, description?: string | null, featured?: boolean | null, bullets?: Array<string | null> | null } | null> | null } | null, process?: { __typename: 'HomeProcess', title?: string | null, steps?: Array<{ __typename: 'HomeProcessSteps', title?: string | null, body?: string | null } | null> | null } | null, authority?: { __typename: 'HomeAuthority', sectionLabel?: string | null, heading?: string | null, body?: string | null } | null, contact?: { __typename: 'HomeContact', heading?: string | null, intro?: string | null, serviceOptions?: Array<string | null> | null, submitLabel?: string | null } | null } | null } | null> | null } };

export type FounderQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type FounderQuery = { __typename?: 'Query', founder: { __typename: 'Founder', id: string, eyebrow?: string | null, heroTitle?: string | null, heroTitleMuted?: string | null, heroSub?: string | null, primaryCtaLabel?: string | null, primaryCtaHref?: string | null, ghostCtaLabel?: string | null, ghostCtaHref?: string | null, founderName?: string | null, founderTitle?: string | null, founderPhoto?: string | null, sidebarLabel?: string | null, sidebarTags?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, content?: Array<{ __typename: 'FounderContentParagraph', text?: string | null } | { __typename: 'FounderContentPullQuote', text?: string | null } | null> | null, cta?: { __typename: 'FounderCta', label?: string | null, heading?: string | null, headingGradient?: string | null, sub?: string | null, primaryCtaLabel?: string | null, primaryCtaHref?: string | null, ghostCtaLabel?: string | null, ghostCtaHref?: string | null } | null } };

export type FounderConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FounderFilter>;
}>;


export type FounderConnectionQuery = { __typename?: 'Query', founderConnection: { __typename?: 'FounderConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'FounderConnectionEdges', cursor: string, node?: { __typename: 'Founder', id: string, eyebrow?: string | null, heroTitle?: string | null, heroTitleMuted?: string | null, heroSub?: string | null, primaryCtaLabel?: string | null, primaryCtaHref?: string | null, ghostCtaLabel?: string | null, ghostCtaHref?: string | null, founderName?: string | null, founderTitle?: string | null, founderPhoto?: string | null, sidebarLabel?: string | null, sidebarTags?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, content?: Array<{ __typename: 'FounderContentParagraph', text?: string | null } | { __typename: 'FounderContentPullQuote', text?: string | null } | null> | null, cta?: { __typename: 'FounderCta', label?: string | null, heading?: string | null, headingGradient?: string | null, sub?: string | null, primaryCtaLabel?: string | null, primaryCtaHref?: string | null, ghostCtaLabel?: string | null, ghostCtaHref?: string | null } | null } | null } | null> | null } };

export type WorkQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type WorkQuery = { __typename?: 'Query', work: { __typename: 'Work', id: string, title?: string | null, titleMuted?: string | null, lead?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, metaPills?: Array<{ __typename: 'WorkMetaPills', label?: string | null, highlight?: boolean | null } | null> | null, overview?: Array<{ __typename: 'WorkOverview', label?: string | null, value?: string | null } | null> | null, sections?: Array<{ __typename: 'WorkSections', sectionLabel?: string | null, navLabel?: string | null, heading?: string | null, paragraphs?: Array<string | null> | null, beforeItems?: Array<string | null> | null, afterItems?: Array<string | null> | null, deliverables?: Array<string | null> | null, callout?: { __typename: 'WorkSectionsCallout', type?: string | null, label?: string | null, body?: string | null } | null, pullQuote?: { __typename: 'WorkSectionsPullQuote', text?: string | null, attribution?: string | null } | null } | null> | null, cta?: { __typename: 'WorkCta', sectionLabel?: string | null, heading?: string | null, headingGradient?: string | null, sub?: string | null } | null } };

export type WorkConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<WorkFilter>;
}>;


export type WorkConnectionQuery = { __typename?: 'Query', workConnection: { __typename?: 'WorkConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'WorkConnectionEdges', cursor: string, node?: { __typename: 'Work', id: string, title?: string | null, titleMuted?: string | null, lead?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, metaPills?: Array<{ __typename: 'WorkMetaPills', label?: string | null, highlight?: boolean | null } | null> | null, overview?: Array<{ __typename: 'WorkOverview', label?: string | null, value?: string | null } | null> | null, sections?: Array<{ __typename: 'WorkSections', sectionLabel?: string | null, navLabel?: string | null, heading?: string | null, paragraphs?: Array<string | null> | null, beforeItems?: Array<string | null> | null, afterItems?: Array<string | null> | null, deliverables?: Array<string | null> | null, callout?: { __typename: 'WorkSectionsCallout', type?: string | null, label?: string | null, body?: string | null } | null, pullQuote?: { __typename: 'WorkSectionsPullQuote', text?: string | null, attribution?: string | null } | null } | null> | null, cta?: { __typename: 'WorkCta', sectionLabel?: string | null, heading?: string | null, headingGradient?: string | null, sub?: string | null } | null } | null } | null> | null } };

export const GlobalPartsFragmentDoc = gql`
    fragment GlobalParts on Global {
  __typename
  nav {
    __typename
    links {
      __typename
      label
      href
      isCta
    }
  }
  footer {
    __typename
    tags
    copyright
  }
}
    `;
export const HomePartsFragmentDoc = gql`
    fragment HomeParts on Home {
  __typename
  hero {
    __typename
    badge
    line1
    line2Prefix
    cyclingWords
    sub
    primaryCtaLabel
    primaryCtaHref
    ghostCtaLabel
    ghostCtaHref
  }
  problem {
    __typename
    heading
    headingMuted
    body
  }
  services {
    __typename
    sectionLabel
    heading
    ctaLabel
    ctaHref
    cards {
      __typename
      number
      title
      description
      featured
      bullets
    }
  }
  process {
    __typename
    title
    steps {
      __typename
      title
      body
    }
  }
  authority {
    __typename
    sectionLabel
    heading
    body
  }
  contact {
    __typename
    heading
    intro
    serviceOptions
    submitLabel
  }
}
    `;
export const FounderPartsFragmentDoc = gql`
    fragment FounderParts on Founder {
  __typename
  eyebrow
  heroTitle
  heroTitleMuted
  heroSub
  primaryCtaLabel
  primaryCtaHref
  ghostCtaLabel
  ghostCtaHref
  founderName
  founderTitle
  founderPhoto
  sidebarLabel
  sidebarTags
  content {
    __typename
    ... on FounderContentParagraph {
      text
    }
    ... on FounderContentPullQuote {
      text
    }
  }
  cta {
    __typename
    label
    heading
    headingGradient
    sub
    primaryCtaLabel
    primaryCtaHref
    ghostCtaLabel
    ghostCtaHref
  }
}
    `;
export const WorkPartsFragmentDoc = gql`
    fragment WorkParts on Work {
  __typename
  title
  titleMuted
  lead
  metaPills {
    __typename
    label
    highlight
  }
  overview {
    __typename
    label
    value
  }
  sections {
    __typename
    sectionLabel
    navLabel
    heading
    paragraphs
    callout {
      __typename
      type
      label
      body
    }
    beforeItems
    afterItems
    deliverables
    pullQuote {
      __typename
      text
      attribution
    }
  }
  cta {
    __typename
    sectionLabel
    heading
    headingGradient
    sub
  }
}
    `;
export const GlobalDocument = gql`
    query global($relativePath: String!) {
  global(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...GlobalParts
  }
}
    ${GlobalPartsFragmentDoc}`;
export const GlobalConnectionDocument = gql`
    query globalConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: GlobalFilter) {
  globalConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...GlobalParts
      }
    }
  }
}
    ${GlobalPartsFragmentDoc}`;
export const HomeDocument = gql`
    query home($relativePath: String!) {
  home(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomeParts
  }
}
    ${HomePartsFragmentDoc}`;
export const HomeConnectionDocument = gql`
    query homeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomeFilter) {
  homeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomeParts
      }
    }
  }
}
    ${HomePartsFragmentDoc}`;
export const FounderDocument = gql`
    query founder($relativePath: String!) {
  founder(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...FounderParts
  }
}
    ${FounderPartsFragmentDoc}`;
export const FounderConnectionDocument = gql`
    query founderConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: FounderFilter) {
  founderConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...FounderParts
      }
    }
  }
}
    ${FounderPartsFragmentDoc}`;
export const WorkDocument = gql`
    query work($relativePath: String!) {
  work(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...WorkParts
  }
}
    ${WorkPartsFragmentDoc}`;
export const WorkConnectionDocument = gql`
    query workConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: WorkFilter) {
  workConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...WorkParts
      }
    }
  }
}
    ${WorkPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      global(variables: GlobalQueryVariables, options?: C): Promise<{data: GlobalQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlobalQueryVariables, query: string}> {
        return requester<{data: GlobalQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlobalQueryVariables, query: string}, GlobalQueryVariables>(GlobalDocument, variables, options);
      },
    globalConnection(variables?: GlobalConnectionQueryVariables, options?: C): Promise<{data: GlobalConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlobalConnectionQueryVariables, query: string}> {
        return requester<{data: GlobalConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlobalConnectionQueryVariables, query: string}, GlobalConnectionQueryVariables>(GlobalConnectionDocument, variables, options);
      },
    home(variables: HomeQueryVariables, options?: C): Promise<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}> {
        return requester<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}, HomeQueryVariables>(HomeDocument, variables, options);
      },
    homeConnection(variables?: HomeConnectionQueryVariables, options?: C): Promise<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}> {
        return requester<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}, HomeConnectionQueryVariables>(HomeConnectionDocument, variables, options);
      },
    founder(variables: FounderQueryVariables, options?: C): Promise<{data: FounderQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FounderQueryVariables, query: string}> {
        return requester<{data: FounderQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FounderQueryVariables, query: string}, FounderQueryVariables>(FounderDocument, variables, options);
      },
    founderConnection(variables?: FounderConnectionQueryVariables, options?: C): Promise<{data: FounderConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FounderConnectionQueryVariables, query: string}> {
        return requester<{data: FounderConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FounderConnectionQueryVariables, query: string}, FounderConnectionQueryVariables>(FounderConnectionDocument, variables, options);
      },
    work(variables: WorkQueryVariables, options?: C): Promise<{data: WorkQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WorkQueryVariables, query: string}> {
        return requester<{data: WorkQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WorkQueryVariables, query: string}, WorkQueryVariables>(WorkDocument, variables, options);
      },
    workConnection(variables?: WorkConnectionQueryVariables, options?: C): Promise<{data: WorkConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WorkConnectionQueryVariables, query: string}> {
        return requester<{data: WorkConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WorkConnectionQueryVariables, query: string}, WorkConnectionQueryVariables>(WorkConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  